spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    connection: jpa
logging:
  level:
    web: warn
    sql: warn
    root: info







